# Generated by Django 6.0.3 on 2026-03-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('condition', models.TextField()),
                ('answer', models.CharField(max_length=200)),
                ('solution', models.TextField()),
            ],
        ),
    ]
