# Generated by Django 6.0.3 on 2026-03-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('condition', models.TextField()),
                ('correct_answer', models.CharField(max_length=100)),
                ('solution', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
