# Generated by Django 6.0.3 on 2026-03-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olymp', '0002_task_delete_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='correct_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='grade',
            field=models.CharField(max_length=10),
        ),
    ]
