# Generated by Django 6.0.3 on 2026-03-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('grade', models.CharField(max_length=10, verbose_name='Класс')),
                ('condition', models.TextField(verbose_name='Условие')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Ответ')),
                ('solution', models.TextField(verbose_name='Решение')),
            ],
        ),
    ]
