# Generated by Django 6.0.2 on 2026-03-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_formula_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='grade',
            field=models.CharField(default=2000, max_length=10, verbose_name='Класс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formula',
            name='year',
            field=models.IntegerField(default=2000, verbose_name='Год'),
            preserve_default=False,
        ),
    ]
