# Generated by Django 6.0.2 on 2026-03-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_formula_grade_formula_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/', verbose_name='Изображение'),
        ),
    ]
